<?php

namespace gestionFondosBundle\Repository;

/**
 * CajasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CajasRepository extends \Doctrine\ORM\EntityRepository
{
}
