<?php

namespace gestionFondosBundle\Repository;

/**
 * CajasBancosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CajasBancosRepository extends \Doctrine\ORM\EntityRepository
{
}
