<?php

namespace gestionFondosBundle\Repository;

/**
 * CajasDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CajasDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
