<?php

namespace gestionFondosBundle\Repository;

/**
 * CajasBancosDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CajasBancosDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
