<?php

namespace gestionFondosBundle\Repository;

use gestionFondosBundle\Entity\Cajas;

/**
 * CajasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CajasRepository extends \Doctrine\ORM\EntityRepository
{
    public function find($id)
    {
        return $this->getDoctrine()->getEntityManager()
            ->createQuery(
                "SELECT * FROM cajas WHERE id='$id'"
            )
            ->getResult();
    }

    public function updateCaja($caja)
    {
        $id = $caja->getId();
        $descripcion = $caja->getDescripcion();
        return $this->getEntityManager()
            ->createQuery(
                "UPDATE gestionFondosBundle:Cajas as caja SET caja.descripcion='$descripcion' WHERE caja.id='$id'"
            )
            ->getResult();
    }
}
