<?php

namespace gestionFondosBundle\Repository;

/**
 * CobradoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CobradoresRepository extends \Doctrine\ORM\EntityRepository
{
}
