<?php

namespace gestionFondosBundle\Repository;

/**
 * ComprobantesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComprobantesRepository extends \Doctrine\ORM\EntityRepository
{
		public function findAll(){
        return $this->getEntityManager()->createQuery("SELECT c.codigo, c.descripcion, c.estado FROM gestionFondosBundle:comprobantes as c")->getResult();
    }
}
