<?php

namespace gestionFondosBundle\Repository;

/**
 * comprobantesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class comprobantesRepository extends \Doctrine\ORM\EntityRepository
{
}
