<?php

namespace gestionFondosBundle\Repository;

/**
 * ConceptosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptosRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAll(){
        return $this->getEntityManager()->createQuery("SELECT c.codigo, c.descripcion, c.estado FROM gestionFondosBundle:conceptos as c")->getResult();
    }
}