<?php

namespace gestionFondosBundle\Repository;

/**
 * CuotasSociosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuotasSociosRepository extends \Doctrine\ORM\EntityRepository
{
}
