<?php

namespace gestionFondosBundle\Repository;

/**
 * FichasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichasRepository extends \Doctrine\ORM\EntityRepository
{
}
