<?php

namespace gestionFondosBundle\Repository;

/**
 * FichaEnCampaniaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichaEnCampaniaRepository extends \Doctrine\ORM\EntityRepository
{
}
