<?php

namespace gestionFondosBundle\Repository;

/**
 * PersonasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonasRepository extends \Doctrine\ORM\EntityRepository
{
    public function personasProveedores(){
        $sql='SELECT p.id FROM gestionFondosBundle:Personas as p WHERE p.apellido = :apellido ORDER BY p.apellido ASC';
        return $this->getEntityManager()->createQuery($sql)->setParameter('apellido', 'apellido')->getResult(); 
    }

    public function findAll(){
        return $this->getDoctrine()->getEntityManager()->createQuery("SELECT nombres FROM personas")->getResult();
    }

    public function find($id)
    {
        return $this->getDoctrine()->getEntityManager()
            ->createQuery(
                "SELECT * FROM personas WHERE id='$id'"
            )
            ->getResult();
    }

    public function updatePersona($persona)
    {
        $id = $persona->getId();
        $email = $persona->getEmail();
        $telefono = $persona->getTelefono();
        $domicilio = $persona->getDomicilio();
        $localidad = $persona->getLocalidad();

        return $this->getEntityManager()
            ->createQuery(
                "UPDATE gestionFondosBundle:Personas as per SET per.email='$email', per.telefono='$telefono', per.domicilio='$domicilio', per.localidad='$localidad' WHERE per.id='$id'"
            )
            ->getResult();
    }
}
