<?php

namespace gestionFondosBundle\Repository;

/**
 * SociosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SociosRepository extends \Doctrine\ORM\EntityRepository
{
}
