<?php

namespace gestionFondosBundle\Repository;

/**
 * SocioEnCampaniaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocioEnCampaniaRepository extends \Doctrine\ORM\EntityRepository
{
}
